Repository uhh-cms/hh2bbtautau, pull requests merged in 2025-01, with the labels that each got.

#57 adding more plotting variables and a default plotting group
  hbt/config/configs_hbt.py
  hbt/config/variables.py
Labels: priority-low, plotting

#60 Fix data shape in qcd hook.
  hbt/config/hist_hooks.py
Labels: enhancement, priority-medium

#61 Add unstitched tags and Datasets for debugging purpose
  hbt/config/configs_hbt.py
  hbt/config/variables.py
  hbt/weight/default.py
Labels: priority-medium, plotting
